export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';
export const TOGGLE_AUDIO = 'TOGGLE_AUDIO';
export const SET_AUDIO_VIDEO_TO_INITIAL_STATE = 'SET_AUDIO_VIDEO_TO_INITIAL_STATE';
